services:
  android-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: android-dev:latest
    container_name: android-dev

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/workspace:rw

      # Terminator 設定をコンテナ内へマウント
      - ../terminator/config:/root/.config/terminator/config:rw
      # 実機 adb / USB 用
      - /dev:/dev

    environment:
      - DISPLAY=${DISPLAY}
      - ANDROID_HOME=/opt/android-sdk
      - ANDROID_USER_HOME=/root/.android
      - ADB_LIBUSB=1

    network_mode: host
    ipc: host
    privileged: true
    devices:
      - /dev:/dev

    command: sleep infinity